"""initial schema

Revision ID: 9fef2ee85dab
Revises: 
Create Date: 2026-04-24 10:45:42.819788

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '9fef2ee85dab'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('daily_quotes',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('ts_code', sa.String(length=16), nullable=False),
    sa.Column('trade_date', sa.Date(), nullable=False),
    sa.Column('open', sa.Float(), nullable=True),
    sa.Column('high', sa.Float(), nullable=True),
    sa.Column('low', sa.Float(), nullable=True),
    sa.Column('close', sa.Float(), nullable=True),
    sa.Column('pre_close', sa.Float(), nullable=True),
    sa.Column('change', sa.Float(), nullable=True),
    sa.Column('pct_chg', sa.Float(), nullable=True),
    sa.Column('vol', sa.Float(), nullable=True),
    sa.Column('amount', sa.Float(), nullable=True),
    sa.Column('turnover_rate', sa.Float(), nullable=True),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('ts_code', 'trade_date', name='uq_daily_quotes_code_date')
    )
    with op.batch_alter_table('daily_quotes', schema=None) as batch_op:
        batch_op.create_index('ix_daily_quotes_date_code', ['trade_date', 'ts_code'], unique=False)
        batch_op.create_index(batch_op.f('ix_daily_quotes_trade_date'), ['trade_date'], unique=False)
        batch_op.create_index(batch_op.f('ix_daily_quotes_ts_code'), ['ts_code'], unique=False)

    op.create_table('intraday_bars',
    sa.Column('id', sa.BigInteger(), autoincrement=True, nullable=False),
    sa.Column('ts_code', sa.String(length=16), nullable=False),
    sa.Column('bar_time', sa.DateTime(), nullable=False),
    sa.Column('open', sa.Float(), nullable=True),
    sa.Column('high', sa.Float(), nullable=True),
    sa.Column('low', sa.Float(), nullable=True),
    sa.Column('close', sa.Float(), nullable=True),
    sa.Column('vol', sa.Float(), nullable=True),
    sa.Column('amount', sa.Float(), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('ts_code', 'bar_time', name='uq_intraday_code_time')
    )
    with op.batch_alter_table('intraday_bars', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_intraday_bars_bar_time'), ['bar_time'], unique=False)
        batch_op.create_index(batch_op.f('ix_intraday_bars_ts_code'), ['ts_code'], unique=False)

    op.create_table('job_runs',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('job_name', sa.String(length=64), nullable=False),
    sa.Column('status', sa.String(length=16), nullable=False),
    sa.Column('message', sa.String(length=512), nullable=True),
    sa.Column('rows_affected', sa.Integer(), nullable=True),
    sa.Column('started_at', sa.DateTime(), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('finished_at', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('job_runs', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_job_runs_job_name'), ['job_name'], unique=False)

    op.create_table('limit_up_daily',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('ts_code', sa.String(length=16), nullable=False),
    sa.Column('trade_date', sa.Date(), nullable=False),
    sa.Column('name', sa.String(length=32), nullable=True),
    sa.Column('close', sa.Float(), nullable=True),
    sa.Column('pct_chg', sa.Float(), nullable=True),
    sa.Column('amount', sa.Float(), nullable=True),
    sa.Column('fd_amount', sa.Float(), nullable=True),
    sa.Column('first_time', sa.String(length=16), nullable=True),
    sa.Column('last_time', sa.String(length=16), nullable=True),
    sa.Column('open_times', sa.Integer(), nullable=True),
    sa.Column('up_stat', sa.String(length=16), nullable=True),
    sa.Column('limit_times', sa.Integer(), nullable=True),
    sa.Column('limit', sa.String(length=8), nullable=True),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('ts_code', 'trade_date', name='uq_limit_up_code_date')
    )
    with op.batch_alter_table('limit_up_daily', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_limit_up_daily_trade_date'), ['trade_date'], unique=False)
        batch_op.create_index(batch_op.f('ix_limit_up_daily_ts_code'), ['ts_code'], unique=False)

    op.create_table('sector_daily',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('sector_code', sa.String(length=32), nullable=False),
    sa.Column('trade_date', sa.Date(), nullable=False),
    sa.Column('name', sa.String(length=64), nullable=True),
    sa.Column('close', sa.Float(), nullable=True),
    sa.Column('pct_chg', sa.Float(), nullable=True),
    sa.Column('vol', sa.Float(), nullable=True),
    sa.Column('amount', sa.Float(), nullable=True),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('sector_code', 'trade_date', name='uq_sector_daily_code_date')
    )
    with op.batch_alter_table('sector_daily', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_sector_daily_sector_code'), ['sector_code'], unique=False)
        batch_op.create_index(batch_op.f('ix_sector_daily_trade_date'), ['trade_date'], unique=False)

    op.create_table('sectors',
    sa.Column('ts_code', sa.String(length=32), nullable=False),
    sa.Column('name', sa.String(length=64), nullable=False),
    sa.Column('type', sa.String(length=16), nullable=False),
    sa.Column('src', sa.String(length=32), nullable=True),
    sa.Column('updated_at', sa.DateTime(), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.PrimaryKeyConstraint('ts_code')
    )
    op.create_table('stocks',
    sa.Column('ts_code', sa.String(length=16), nullable=False),
    sa.Column('symbol', sa.String(length=16), nullable=False),
    sa.Column('name', sa.String(length=32), nullable=False),
    sa.Column('area', sa.String(length=32), nullable=True),
    sa.Column('industry', sa.String(length=64), nullable=True),
    sa.Column('market', sa.String(length=16), nullable=True),
    sa.Column('list_date', sa.Date(), nullable=True),
    sa.Column('is_active', sa.Integer(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.PrimaryKeyConstraint('ts_code')
    )
    with op.batch_alter_table('stocks', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_stocks_symbol'), ['symbol'], unique=False)

    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('stocks', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_stocks_symbol'))

    op.drop_table('stocks')
    op.drop_table('sectors')
    with op.batch_alter_table('sector_daily', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_sector_daily_trade_date'))
        batch_op.drop_index(batch_op.f('ix_sector_daily_sector_code'))

    op.drop_table('sector_daily')
    with op.batch_alter_table('limit_up_daily', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_limit_up_daily_ts_code'))
        batch_op.drop_index(batch_op.f('ix_limit_up_daily_trade_date'))

    op.drop_table('limit_up_daily')
    with op.batch_alter_table('job_runs', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_job_runs_job_name'))

    op.drop_table('job_runs')
    with op.batch_alter_table('intraday_bars', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_intraday_bars_ts_code'))
        batch_op.drop_index(batch_op.f('ix_intraday_bars_bar_time'))

    op.drop_table('intraday_bars')
    with op.batch_alter_table('daily_quotes', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_daily_quotes_ts_code'))
        batch_op.drop_index(batch_op.f('ix_daily_quotes_trade_date'))
        batch_op.drop_index('ix_daily_quotes_date_code')

    op.drop_table('daily_quotes')
    # ### end Alembic commands ###
