"""add stock_sectors table

Revision ID: ebb7225fb4c3
Revises: 9fef2ee85dab
Create Date: 2026-04-24 17:05:33.645622

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'ebb7225fb4c3'
down_revision: Union[str, Sequence[str], None] = '9fef2ee85dab'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('stock_sectors',
    sa.Column('ts_code', sa.String(length=16), nullable=False),
    sa.Column('sector_code', sa.String(length=32), nullable=False),
    sa.Column('src', sa.String(length=16), nullable=True),
    sa.Column('updated_at', sa.DateTime(), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.PrimaryKeyConstraint('ts_code', 'sector_code')
    )
    with op.batch_alter_table('stock_sectors', schema=None) as batch_op:
        batch_op.create_index('ix_stock_sectors_sector', ['sector_code'], unique=False)

    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('stock_sectors', schema=None) as batch_op:
        batch_op.drop_index('ix_stock_sectors_sector')

    op.drop_table('stock_sectors')
    # ### end Alembic commands ###
