"""add journal tables (trading/review/master)

Revision ID: f44eb6bd19c6
Revises: ebb7225fb4c3
Create Date: 2026-04-24 17:36:27.881941

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'f44eb6bd19c6'
down_revision: Union[str, Sequence[str], None] = 'ebb7225fb4c3'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('master_tracking',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('entry_date', sa.Date(), nullable=False),
    sa.Column('content', sa.Text(), nullable=False),
    sa.Column('images', sa.Text(), nullable=False),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('updated_at', sa.DateTime(), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('master_tracking', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_master_tracking_entry_date'), ['entry_date'], unique=False)

    op.create_table('review_references',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('entry_date', sa.Date(), nullable=False),
    sa.Column('content', sa.Text(), nullable=False),
    sa.Column('images', sa.Text(), nullable=False),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('updated_at', sa.DateTime(), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('review_references', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_review_references_entry_date'), ['entry_date'], unique=False)

    op.create_table('trading_records',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('entry_date', sa.Date(), nullable=False),
    sa.Column('content', sa.Text(), nullable=False),
    sa.Column('images', sa.Text(), nullable=False),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('updated_at', sa.DateTime(), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('trading_records', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_trading_records_entry_date'), ['entry_date'], unique=False)

    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('trading_records', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_trading_records_entry_date'))

    op.drop_table('trading_records')
    with op.batch_alter_table('review_references', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_review_references_entry_date'))

    op.drop_table('review_references')
    with op.batch_alter_table('master_tracking', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_master_tracking_entry_date'))

    op.drop_table('master_tracking')
    # ### end Alembic commands ###
